### ISSUE TITLE
Add test for GzipSource::updateCrc@186-201@GzipSource.java

### ISSUE THREAD

**Issue by ZiadP** [Abdallahassan/okio#19]
The part where:
<img width="582" alt="screen shot 2018-02-25 at 16 51 38" src="https://user-images.githubusercontent.com/35456094/36643470-2af5c8f8-1a4c-11e8-9fce-7e034a6e9792.png">
is not covered.

**Comment by pola** [comment]
I apologise for all the many pull requests, but finally I think I got it working.

**Comment by pola** [comment]
The pull request was merged. Thank you!
